//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_PrimarcyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> Amounth { get; set; }
        public Nullable<System.DateTime> PurcasheDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
